#!/usr/bin/env bash
# Start/Stops/Restarts. Script to be used with manage_my_process

argv1=$1
tmpfile="/var/run/my_process.pid"

startLoop_n_createFile()
{
    ./manage_my_process &
    echo "$!" > "$tmpfile"
}
killLoop_n_rmFile()
{
    #kill "$(cat "$tmpfile")"
    sudo pkill -f "./manage_my_process"
    rm "$tmpfile"
}
case "$argv1" in
    start) echo "manage_my_process started"
	startLoop_n_createFile
	;;
    stop) echo "manage_my_process stopped"
	killLoop_n_rmFile
	;;
    restart) echo "manage_my_process restarted"
	killLoop_n_rmFile
	startLoop_n_createFile
	;;
    *) echo "Usage: manage_my_process {start|stop|restart}"
	;;
esac
