#!/usr/bin/env bash
# Script receives kill signal from another script running in another terminal
# Kill signal is caught and ignored; printing message instead

msg()
{
    echo "I am invincible!!!"
}
trap "msg" SIGTERM

while true
do
    echo "To infinity and beyond"
    sleep 2

done
